apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-rollouts-demo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: canary
    repoURL: 'https://github.com/raphaelg-cit/rollouts-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
